- forwarder/kafka/kafka_helpers.py
- forwarder/kafka/kafka_producer.py
- forwarder/status_reporter.py
- manual_testing/add_ca_config.py
- manual_testing/add_fake_config.py
- manual_testing/add_pva_config.py
- system_tests/compose/docker-compose-kafka.yml
- system_tests/test_forwarding.py
> Set kafka message header timestamps

- system_tests/helpers/flatbuffer_helpers.py
- system_tests/test_forwarding.py
- system_tests/test_generate_fake_epics_data.py
- system_tests/test_idle_pv_updates.py
- system_tests/test_longrunning.py
I had to do this to get the system tests to run from the command line.
Were other people able to run them before?
I'm using relative imports, so sorry if that makes you barf!
> Fixing imports

- Jenkinsfile
> Add black, flake8 and mypy checks to Jenkins job

- system_tests/conftest.py
It still fails on Mac but this, at least, gets it starting.
Can you try it on Linux please?
> Running system-tests against local build has some "legacy" details.

- forwarder/application_logger.py
- forwarder_launch.py
Just a crude implementation so @amues can try it in the integration tests.
> Allow setting of graylog server details

- .dockerignore
- forwarder/status_reporter.py
- forwarder_launch.py
- setup.cfg
- tests/status_reporter_test.py
Closes #31
Gets version number from setup.cfg and uses it in status messages and prints if `--version` flag is used.
> Forwarder gets version number from setup.cfg

- forwarder/parse_config_update.py
- forwarder_launch.py
- requirements.txt
- setup.cfg
- system_tests/compose/docker-compose-kafka.yml
- system_tests/helpers/forwarderconfig.py
- system_tests/helpers/producerwrapper.py
- system_tests/test_forwarding.py
- tests/parse_config_update_test.py
DM-1901
Use new schema for configuration change messages.
Added unit tests for parsing the messages and updated the system tests.
> Use FlatBuffer configuration change messages

- .gitignore
- Jenkinsfile
- README.md
- codecov.yml
- forwarder/update_handlers/create_update_handler.py
- forwarder/update_handlers/fake_update_handler.py
- requirements-dev.txt
- tests/kafka/fake_producer.py
- tests/update_handlers/create_update_handler_test.py
- tests/update_handlers/fake_update_handler_test.py
- tests/update_handlers/pva_update_handler_test.py
Remainder of coverage should be addressed by #41
> Add test coverage reporting using codecov

- tests/test_helpers/ca_fakes.py
- tests/update_handlers/ca_update_handler_test.py
- tests/update_handlers/create_update_handler_test.py
Closes #41 
Unit tests for the `CAUpdateHandler`
> CAUpdateHandler test coverage

- README.md
- changes.md
- forwarder/parse_commandline_args.py
Started making the documentation more standalone and added more info.
Not perfect, but moving in the right direction hopefully.
> Improve documentation

- .pre-commit-config.yaml
Match change https://github.com/ess-dmsc/python-streaming-data-types/pull/25
> Use official flake8 repo precommit hook

- README.md
- changes.md
- forwarder/kafka/kafka_helpers.py
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- requirements.txt
- tests/kafka/kafka_helpers_test.py
- tests/update_handlers/ca_update_handler_test.py
- tests/update_handlers/pva_update_handler_test.py
Closes DM-1997
Added unit test and implemented.
> Update to new chopper timestamp scheme

- changes.md
- forwarder/kafka/kafka_helpers.py
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- manual_testing/add_ca_config.py
- manual_testing/add_fake_config.py
- manual_testing/add_pva_config.py
- tests/test_helpers/ca_fakes.py
- tests/test_helpers/p4p_fakes.py
- tests/update_handlers/ca_update_handler_test.py
- tests/update_handlers/pva_update_handler_test.py
Closes #3 
Unit tests and implementation of publishing connection state changes for CA and PVA.
> Produce epics connection status messages

- requirements.txt
> Streaming data types update

- forwarder/handle_config_change.py
- forwarder/kafka/kafka_helpers.py
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- forwarder_launch.py
Plus one replacement of dict() with {}
> Mostly changes to the comments to make the lines shorter.

- forwarder/handle_config_change.py
- forwarder/parse_config_update.py
- tests/handle_config_change_test.py
- tests/parse_config_update_test.py
Make it more general so it can cover messages with the incorrect schema etc.
> Replace MALFORMED with INVALID

- .github/dependabot.yml
- requirements-dev.txt
- requirements.txt
Let's see what happens!
I've pinned everything in the requirements.txt and, as some of those are not the most recent, it should trigger in the next day or so
> Add dependabot support

- forwarder/parse_commandline_args.py
- forwarder/statistics_reporter.py
- forwarder_launch.py
- requirements.txt
- tests/statistic_reporter_test.py
This PR implements functionality to send number of configured PVs to the Graphite server.  Attached is an ugly screenshot from Graphite dashboard.
> Ecdc 1594 Grafana statistic support

- forwarder/application_logger.py
- forwarder_launch.py
This PR may address the issue https://github.com/ess-dmsc/forwarder/issues/6
@mattclarke
> Friendly error message if logging directory does not exist

- forwarder/kafka/kafka_producer.py
Writing error message to kafka producer logger.
> Added handling for BufferError exception

- README.md
> Correct link for the readme buildpass badge

- forwarder/update_handlers/base_update_handler.py
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/fake_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- tests/update_handlers/base_update_handler_test.py
- tests/update_handlers/ca_update_handler_test.py
- tests/update_handlers/pva_update_handler_test.py
Add some simple timestamp filtering to remove obviously bad EPICS timestamps.
> Timestamp filtering

- changes.md
- forwarder/update_handlers/base_update_handler.py
- forwarder/update_handlers/nttable_senv_serialiser.py
- requirements.txt
> Performance improvement and bug fix

- changes.md
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
Added logging of run-time and value exceptions in the PVA/CA update handling code.
> Ecdc 2701 improve log messages

- changes.md
- forwarder/update_handlers/ep00_serialiser.py
- tests/update_handlers/ep00_serialiser_test.py
As the title says. Is not yet integrated with the rest of the code.
> Connection status serialiser module

- forwarder/kafka/kafka_producer.py
- forwarder/repeat_timer.py
- forwarder/update_handlers/base_update_handler.py
- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- forwarder_launch.py
This PR makes most exceptions guaranteed to be logged. _I think._
> ECDC-2841 guaranteed logging

- forwarder/update_handlers/ca_update_handler.py
- forwarder/update_handlers/pva_update_handler.py
- requirements-dev.txt
- requirements.txt
- system_tests/helpers/ca_ioc.py
- system_tests/helpers/pva_ioc.py
- system_tests/test_idle_pv_updates.py
- tests/test_helpers/ca_fakes.py
Check and warn about changing units.
I have added no unit or system tests for this new functionality as I think it is too much work for too little effort to test this. I can add one though if you insist.
> Ecdc 1284 check units

- README.md
- forwarder/kafka/kafka_helpers.py
- forwarder/parse_commandline_args.py
- tests/kafka/kafka_helpers_test.py
Fixing bug introduced by https://github.com/ess-dmsc/forwarder/pull/173
> Fix: SASL should be disabled by default

- Jenkinsfile
- forwarder_launch.py
Bug introduced with refactoring code here:
52d86e6e47588a3610b11f7a31c9c20d17ae47ae
> Fix(launch): Statistics reporter uses non-existent parameter

- forwarder/update_handlers/schema_serialiser_factory.py
I missed that there was a new factory file that I forgot to update for the addition of se00.
> adding se00 to the schema factory

- forwarder/update_handlers/nttable_se00_serialiser.py
- tests/update_handlers/nttable_se00_test.py
> se00 forwarder fix and updated unittest
