forwarder/kafka/kafka_producer.py

Solves a problem I saw when using the manual test scripts where occasionally the producer was closed before it had published a message.

Give producer opportunity to clear its queue before closing

---

forwarder/epics_to_serialisable_types.py
forwarder/kafka/kafka_producer.py
forwarder/update_handlers/ca_update_handler.py

Closes #10
Before: used system time when the monitor callback triggered as the timestamp for CA PV updates.
After: Uses timestamp from EPICS

Use caproto "time" data_type to get time and alarm info

---

forwarder_launch.py
system_tests/config-files/forwarder_config_fake_epics.ini
system_tests/config-files/forwarder_config_forwarding.ini
system_tests/config-files/forwarder_config_idle_updates.ini
system_tests/config-files/forwarder_config_lr.ini

Closes #27 
Now must provide `--output-broker` explicitly; it has no default.
System test run configs updated accordingly.

Make explicitly setting output broker required

---

forwarder/status_reporter.py
forwarder_launch.py
tests/status_reporter_test.py

I started adding unit tests for StatusReporter in preparation for producing flatbuffer status messages, but we won't be able to merge that until the File Writer and NICOS are ready so we may as well merge unit tests for the existing implementation now.

Add unit tests for StatusReporter

---

forwarder/update_handlers/ca_update_handler.py
requirements.txt

and removed comment in the code about the old behaviour.
Closes #2

Require latest version of caproto so subscribe does not block if PV not currently available

---

forwarder/update_handlers/pva_update_handler.py
system_tests/compose/docker-compose-kafka.yml
system_tests/test_forwarding.py
tests/update_handlers/pva_update_handler_test.py

Closes #34 
(DM-1864 also resolved by updating softioc)
- Adds system test for forwarding arrays.
- Adds unit test and fix for forwarding PVA array updates.
- Set initial values of PVs in a "setup" function during system tests, so that they are independent of initial value set in the softioc.
- softioc container was updated to remove SCAN field from the arrays, which was making it difficult to test.

Test forwarding arrays

---

forwarder/parse_config_update.py

This patch prevents that an ill-formatted or an empty command crashes the forwarder.
Closes #7

Fix invalid command causes crash

---

forwarder/status_reporter.py
forwarder_launch.py
system_tests/test_forwarding.py
tests/status_reporter_test.py

Closes #25 
Part of DM-1896
Produces FlatBuffer serialised status messages instead of just utf-8 encoded JSON.
`StatusReporter` unit tests are updated.

FlatBuffer status messages

---

forwarder/application_logger.py
forwarder/handle_config_change.py
forwarder/parse_commandline_args.py
forwarder/parse_config_update.py
forwarder/status_reporter.py
forwarder/update_handlers/create_update_handler.py
forwarder_launch.py
requirements.txt
system_tests/compose/docker-compose-kafka.yml
tests/handle_config_change_test.py
tests/parse_config_update_test.py
tests/status_reporter_test.py

Closes #39
Closes #38 
Use full Channel object as update_handlers dictionary key instead of only the pv name. This allows multiple configurations for the same pv name, for example to serialise updates with different schemas or output to multiple topics (#38). It also allows removing configurations matching any subset of pv name, output topic and schema (#39).
I also extracted config change handling to a separate file so that I could add unit tests.

Allow removing handlers by name, topic and/or schema

---

README.md
changes.md
forwarder/handle_config_change.py
system_tests/README.md
tests/handle_config_change_test.py

Closes DM-1634
Unit tests and impl use of single- or multi-character wildcards when matching output topic or channel names to remove existing configurations.

Allow wildcards when removing configurations by topic or channel name

---

changes.md
system_tests/compose/docker-compose-kafka.yml
system_tests/compose/docker-compose-storage.yml
system_tests/config-files/forwarder_config_storage.ini
system_tests/conftest.py
system_tests/test_config_storage.py

Ugly little test to check that the stored config is retrieved on start-up.
Test for checking that they are saved is not required as that is covered in the unit tests (handle_config_change_test.py).

Added system test to check stored config is retrieved on start-up.

---

forwarder/parse_commandline_args.py

`forwarder_launch.py --version` should work when executed from any directory.

Avoid using cwd to find setup.cfg to get version

---

.pre-commit-config.yaml
requirements-dev.txt

~Rebase on master after #57 is merged.~ done
We've had problems with precommit hook versions not matching what is used in the CI checks. Pinning both solves this problem, although we'll have to remember to update them every so often.

Update precommit hooks and static analysis tool versions

---

forwarder/parse_config_update.py
requirements.txt
system_tests/conftest.py

The python-streaming-data-types module changed to throw exceptions if the schema is wrong, this change allows us to support it.

Handle exception when message has wrong schema

---

system_tests/helpers/epics_helpers.py
system_tests/test_forwarding.py

Closes #63 
Retries setting initial PV values up to 10 times. This stops the system tests from failing if the SoftIOC container is slower to start than the Kafka broker.

Make systemtests robust to slow SoftIOC startup

---

forwarder/update_handlers/ca_update_handler.py
forwarder/update_handlers/pva_update_handler.py

Can get an error warning about self._pv_name not being defined if monitor_callback happens before the value is defined.
Simple fix is to move the assignment up before trying to create the monitor.
<update>
Some of the other variables are used in the callback too, so I've moved them all up too.

Fix minor race condition

---

forwarder/status_reporter.py
system_tests/README.md
system_tests/test_forwarding.py

This PR may address the issue mentioned in https://github.com/ess-dmsc/forwarder/issues/44
I added all the Channel attributes in the status msg as mentioned in the issue. I hope this is ok.
@mattclarke  
@matthew-d-jones

Add more channel info in status msg

---

Jenkinsfile
requirements-dev.txt
requirements.txt
tox.ini

pip complains that the numpy version conflicts with the requirements for p4p (on the build server anyway, I don't see the same issue on mac)

Bumped numpy version

---

Jenkinsfile
forwarder/configuration_store.py
forwarder/kafka/kafka_helpers.py
forwarder/kafka/kafka_producer.py
forwarder/parse_config_update.py
forwarder/update_handlers/base_update_handler.py
forwarder/update_handlers/ca_update_handler.py
forwarder/update_handlers/f142_serialiser.py
forwarder/update_handlers/fake_update_handler.py
forwarder/update_handlers/nttable_senv_serialiser.py
forwarder/update_handlers/pva_update_handler.py
forwarder/update_handlers/schema_publishers.py
forwarder/update_handlers/schema_serialisers.py
forwarder/update_handlers/tdct_serialiser.py
requirements.txt
system_tests/test_forwarding.py
tests/kafka/kafka_helpers_test.py
tests/update_handlers/base_update_handler_test.py
tests/update_handlers/ca_update_handler_test.py
tests/update_handlers/fake_update_handler_test.py
tests/update_handlers/nttable_senv_test.py
tests/update_handlers/pva_update_handler_test.py
tests/update_handlers/tdct_test.py

This required more changes than I had initially thought. A general outline follows:
* Moved flatbuffer serialisation into classes to modularise the code.
* Removed serialisation of enums as strings to conform to the NeXus standard and the file-writer implementation.
* Changed responsibility for value extraction from ca/pva handlers to the serialisation code.
* Implemented conversion of (some specific) NTTables  into senv flatbuffers.
On top of that I also had to implement some bug fixes and other minor improvements to make the tests run properly.

Implement NTTable to senv

---

changes.md
forwarder/update_handlers/base_update_handler.py
forwarder/update_handlers/ca_update_handler.py
forwarder/update_handlers/f142_serialiser.py
forwarder/update_handlers/pva_update_handler.py
tests/update_handlers/ca_update_handler_test.py

* Fixed bug where the wrong type was picked when casting numpy arrays in the f142 serialiser.
* Known bad PV updates will no longer be cached for (attempted) re-transmission.

Two bug fixes.

---

forwarder_launch.py

The dots cause the metric names to be broken into additional components.

Replace dots in hostnames for metrics

---

requirements-dev.txt

We are having build issues with the latest major tox version (4), as it seems to tries to create environments inside existing ones, eventually exhausting the available disk space in builds.

Pin tox version in requirements-dev.txt

---

forwarder/parse_config_update.py
requirements.txt
tests/parse_config_update_test.py

PSDT has been updated to a newer flatbuffers version.
Also, removed any direct dependency on flatbuffers from this application. There is little point to using an abstraction (PSDT) if we are going to let things (flatbuffers) leak through it ;)

updated psdt version

---

forwarder/update_handlers/ep01_serialiser.py
tests/update_handlers/ep01_serialiser_test.py
tests/update_handlers/pva_update_handler_test.py

For p4p the Value class was not in the map, so even if the PV was connected it appeared as unknown.
It is a one line fix, but I added a regression test for it and fixed up the related tests. 
If a PV never connected then it doesn't send anything to Kafka.

ECDC-3313: Fix ep01 bug 
